apiVersion: v1
kind: Pod
metadata:
  name: spiffe-client
  namespace: default
spec:
  serviceAccountName: default
  containers:
    - name: client
      image: ghcr.io/spiffe/spire-agent:1.14.5
      command:
        - /opt/spire/bin/spire-agent
        - api
        - watch
        - -socketPath
        - /run/spire/sockets/spire-agent.sock
      volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
  volumes:
    - name: spire-agent-socket
      csi:
        driver: "csi.spiffe.io"
        readOnly: true
